/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.microkernel.gestionproyectos.presentation;

import co.edu.unicauca.microkernel.entities.Project;
import co.edu.unicauca.microkernel.entities.User;
import co.edu.unicauca.microkernel.interfaces.IProjectRepositoryPlugin;
import co.edu.unicauca.microkernel.interfaces.observer;
import co.unicauca.microkernel.gestionproyectos.core.domain.services.ProjectService;
import co.unicauca.microkernel.gestionproyectos.core.plugin.manager.PluginManager;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lopez
 */
public class HomeProject extends javax.swing.JFrame implements observer {

    private IProjectRepositoryPlugin repositorio;
    private User user;
    private List<User> Users = new ArrayList<>();
    private ProjectService project; // Solo la declaración

    /**
     * Creates new form HomeProject
     */
    public HomeProject(IProjectRepositoryPlugin plugin) {
        initComponents();
        this.repositorio = plugin;
        this.project = new ProjectService(plugin);
        this.Users = user.getUser();
        this.project.addObserver(this);
        fillTableProject();
        fillTableUser();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBody = new javax.swing.JPanel();
        jPLateralMenu = new javax.swing.JPanel();
        jLMenu = new javax.swing.JLabel();
        jBtnRegisterProject = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jBtnAsignarEstudiante = new javax.swing.JButton();
        jBtnRegistrarUsuario1 = new javax.swing.JButton();
        jPContent = new javax.swing.JPanel();
        jPCompany = new javax.swing.JPanel();
        jLProject = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjects = new javax.swing.JTable();
        jPStudent = new javax.swing.JPanel();
        Usuarios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        jPHead = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPBody.setBackground(new java.awt.Color(255, 255, 255));

        jPLateralMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPLateralMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLMenu.setForeground(new java.awt.Color(0, 0, 0));
        jLMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMenu.setText("MENU");
        jPLateralMenu.add(jLMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, -1));

        jBtnRegisterProject.setBackground(new java.awt.Color(0, 0, 0));
        jBtnRegisterProject.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnRegisterProject.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegisterProject.setText("Registrar proyecto");
        jBtnRegisterProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegisterProjectActionPerformed(evt);
            }
        });
        jPLateralMenu.add(jBtnRegisterProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 50));

        jBtnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnBack.setText("ATRAS");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });
        jPLateralMenu.add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jBtnAsignarEstudiante.setBackground(new java.awt.Color(0, 0, 0));
        jBtnAsignarEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnAsignarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAsignarEstudiante.setText("Asignar Estudiante");
        jBtnAsignarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAsignarEstudianteActionPerformed(evt);
            }
        });
        jPLateralMenu.add(jBtnAsignarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, 50));

        jBtnRegistrarUsuario1.setBackground(new java.awt.Color(0, 0, 0));
        jBtnRegistrarUsuario1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnRegistrarUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegistrarUsuario1.setText("Registrar Usuario");
        jBtnRegistrarUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarUsuario1ActionPerformed(evt);
            }
        });
        jPLateralMenu.add(jBtnRegistrarUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 50));

        jPContent.setBackground(new java.awt.Color(204, 204, 204));

        jPCompany.setBackground(new java.awt.Color(255, 255, 255));

        jLProject.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLProject.setForeground(new java.awt.Color(0, 0, 0));
        jLProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLProject.setText("Proyectos");

        jTableProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProjects);

        javax.swing.GroupLayout jPCompanyLayout = new javax.swing.GroupLayout(jPCompany);
        jPCompany.setLayout(jPCompanyLayout);
        jPCompanyLayout.setHorizontalGroup(
            jPCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCompanyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPCompanyLayout.setVerticalGroup(
            jPCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCompanyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );

        jPStudent.setBackground(new java.awt.Color(255, 255, 255));

        Usuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuarios.setForeground(new java.awt.Color(0, 0, 0));
        Usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuarios.setText("Usuarios");

        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableUser);

        javax.swing.GroupLayout jPStudentLayout = new javax.swing.GroupLayout(jPStudent);
        jPStudent.setLayout(jPStudentLayout);
        jPStudentLayout.setHorizontalGroup(
            jPStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPStudentLayout.createSequentialGroup()
                .addGroup(jPStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPStudentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPStudentLayout.setVerticalGroup(
            jPStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Usuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPContentLayout = new javax.swing.GroupLayout(jPContent);
        jPContent.setLayout(jPContentLayout);
        jPContentLayout.setHorizontalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPContentLayout.setVerticalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );

        javax.swing.GroupLayout jPBodyLayout = new javax.swing.GroupLayout(jPBody);
        jPBody.setLayout(jPBodyLayout);
        jPBodyLayout.setHorizontalGroup(
            jPBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBodyLayout.createSequentialGroup()
                .addComponent(jPLateralMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPBodyLayout.setVerticalGroup(
            jPBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPLateralMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPHead.setBackground(new java.awt.Color(255, 255, 255));
        jPHead.setLayout(new java.awt.BorderLayout());

        jLTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setText("Proyecto de microKernel");
        jPHead.add(jLTitulo, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBody, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        List<IProjectRepositoryPlugin> listaPlugins = PluginManager.getPlugins();
        Home home = new Home(listaPlugins);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnRegisterProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegisterProjectActionPerformed
        List<User> empresas = new ArrayList<>();
        for (User user : Users) {
            if (user.getRole() == "EMPRESA") {
                empresas.add(user);
            }
        }
        newProject project = new newProject(empresas, repositorio);
        project.setVisible(true);
    }//GEN-LAST:event_jBtnRegisterProjectActionPerformed

    private void jBtnAsignarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAsignarEstudianteActionPerformed
       List<User> estudiantes = new ArrayList<>();
       List<Project> proyectos = new ArrayList<>();
       
        for (User user : Users) {
            if (user.getRole() == "ESTUDIANTE") {
                estudiantes.add(user);
            }
        }
        for (Project project : repositorio.getProjects()){
            proyectos.add(project);
        }
        newAssignment assignment = new newAssignment(estudiantes, proyectos, repositorio);
        assignment.setVisible(true);
    }//GEN-LAST:event_jBtnAsignarEstudianteActionPerformed

    private void jBtnRegistrarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarUsuario1ActionPerformed
        // TODO add your handling code here:
        newUser user = new newUser(Users);
        user.setVisible(true);
    }//GEN-LAST:event_jBtnRegistrarUsuario1ActionPerformed

    public void fillTableProject() {
        DefaultTableModel modeloProyectos = new DefaultTableModel(new String[]{"Titulo", "Descripcion", "Comapañia", "Estudiante encargado"}, 0);
        modeloProyectos.setRowCount(0);

        for (Project project : repositorio.getProjects()) {

            if (project.getStudent() != null && project.getStudent().getName() != null) {
                modeloProyectos.addRow(new Object[]{project.getTitle(), project.getDescription(), project.getCompany().getName(), project.getStudent().getName()});
            } else {
                modeloProyectos.addRow(new Object[]{project.getTitle(), project.getDescription(), project.getCompany().getName(), "no tiene"});
            }
        }
        jTableProjects.setModel(modeloProyectos);
    }

    public void fillTableUser() {
        DefaultTableModel modeloUser = new DefaultTableModel(new String[]{"Nombre", "email", "rol"}, 0);
        modeloUser.setRowCount(0);

        for (User user : Users) {
            modeloUser.addRow(new Object[]{user.getName(), user.getEmail(), user.getRole()});
        }
        jTableUser.setModel(modeloUser);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Usuarios;
    private javax.swing.JButton jBtnAsignarEstudiante;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnRegisterProject;
    private javax.swing.JButton jBtnRegistrarUsuario1;
    private javax.swing.JLabel jLMenu;
    private javax.swing.JLabel jLProject;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPBody;
    private javax.swing.JPanel jPCompany;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPLateralMenu;
    private javax.swing.JPanel jPStudent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProjects;
    private javax.swing.JTable jTableUser;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        fillTableUser();
        fillTableProject();
        System.out.println("Tablas actualizadas por medio del observer");
    }
}
