/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.microkernel.gestionproyectos.presentation;

import co.edu.unicauca.microkernel.interfaces.IProjectRepositoryPlugin;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author lopez
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home(List<IProjectRepositoryPlugin> listaPlugins) {
        initComponents();
        llenarPlugins(listaPlugins);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPHead = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jPBody = new javax.swing.JPanel();
        jLSelectPlugin = new javax.swing.JLabel();
        jCBSeleccionarPlugin = new javax.swing.JComboBox<>();
        jBtnSelectPlugin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPHead.setBackground(new java.awt.Color(255, 255, 255));
        jPHead.setLayout(new java.awt.BorderLayout());

        jLTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setText("Proyecto de microKernel");
        jPHead.add(jLTitulo, java.awt.BorderLayout.CENTER);

        jPBody.setBackground(new java.awt.Color(255, 255, 255));

        jLSelectPlugin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLSelectPlugin.setForeground(new java.awt.Color(0, 0, 0));
        jLSelectPlugin.setText("Seleccione el plugin para guardar los proyectos:");

        jCBSeleccionarPlugin.setBackground(new java.awt.Color(255, 255, 255));
        jCBSeleccionarPlugin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCBSeleccionarPlugin.setForeground(new java.awt.Color(0, 0, 0));
        jCBSeleccionarPlugin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBtnSelectPlugin.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSelectPlugin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnSelectPlugin.setForeground(new java.awt.Color(0, 0, 0));
        jBtnSelectPlugin.setText("Seleccionar");
        jBtnSelectPlugin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelectPluginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBodyLayout = new javax.swing.GroupLayout(jPBody);
        jPBody.setLayout(jPBodyLayout);
        jPBodyLayout.setHorizontalGroup(
            jPBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBodyLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLSelectPlugin)
                .addGap(70, 70, 70))
            .addGroup(jPBodyLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jBtnSelectPlugin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBSeleccionarPlugin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBodyLayout.setVerticalGroup(
            jPBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBodyLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLSelectPlugin)
                .addGap(27, 27, 27)
                .addComponent(jCBSeleccionarPlugin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jBtnSelectPlugin)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSelectPluginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelectPluginActionPerformed
        String selectedName = (String) jCBSeleccionarPlugin.getSelectedItem();
        IProjectRepositoryPlugin selectedPlugin = pluginMap.get(selectedName);

        if (selectedPlugin != null) {
            HomeProject homeproject = new HomeProject(selectedPlugin);
            homeproject.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un plugin válido.");
        }
    }//GEN-LAST:event_jBtnSelectPluginActionPerformed

    private HashMap<String, IProjectRepositoryPlugin> pluginMap = new HashMap<>();

    public void llenarPlugins(List<IProjectRepositoryPlugin> listaPlugins) {
        jCBSeleccionarPlugin.removeAllItems();
        pluginMap.clear(); // Limpiar el mapa antes de llenarlo

        for (IProjectRepositoryPlugin plugin : listaPlugins) {
            String nombrePlugin = plugin.getClass().getSimpleName();
            pluginMap.put(nombrePlugin, plugin);
            jCBSeleccionarPlugin.addItem(nombrePlugin);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSelectPlugin;
    private javax.swing.JComboBox<String> jCBSeleccionarPlugin;
    private javax.swing.JLabel jLSelectPlugin;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPBody;
    private javax.swing.JPanel jPHead;
    // End of variables declaration//GEN-END:variables
}
