
package co.unicauca.microkernel.gestionproyectos.presentation;

import co.edu.unicauca.microkernel.entities.Project;
import co.edu.unicauca.microkernel.entities.User;
import co.edu.unicauca.microkernel.interfaces.IProjectRepositoryPlugin;
import co.edu.unicauca.microkernel.microkernel_plugin.Plugin_ArrayList;
import co.unicauca.microkernel.gestionproyectos.access.ProjectsRepositoryArrayPlugin;
import co.unicauca.microkernel.gestionproyectos.core.domain.services.ProjectService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class newAssignment extends javax.swing.JFrame {

    private IProjectRepositoryPlugin repositorio;
    private List<User> UsersStudents = new ArrayList<>();
    private List<Project> NameProyects = new ArrayList<>();
    /**
     * Creates new form newAssignment
     */
    public newAssignment(List<User> estudiantes,List<Project> proyectos, IProjectRepositoryPlugin plugin) {
        initComponents();
        this.UsersStudents = estudiantes;
        this.NameProyects = proyectos;
        this.repositorio = plugin;
        fillStudents();
        fillProyects();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPTittleNewAssignament = new javax.swing.JPanel();
        jLTittleNewCompany = new javax.swing.JLabel();
        jPContent = new javax.swing.JPanel();
        jLNameProyect = new javax.swing.JLabel();
        jLSectorStudent = new javax.swing.JLabel();
        jCBProyects = new javax.swing.JComboBox<>();
        jBtnSaveProject = new javax.swing.JButton();
        jCBStudents = new javax.swing.JComboBox<>();
        jPButtom = new javax.swing.JPanel();
        jPHead = new javax.swing.JPanel();
        lbTitleProyect = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPTittleNewAssignament.setBackground(new java.awt.Color(255, 255, 255));

        jLTittleNewCompany.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLTittleNewCompany.setForeground(new java.awt.Color(0, 0, 0));
        jLTittleNewCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittleNewCompany.setText("Nueva Asignación");
        jLTittleNewCompany.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPTittleNewAssignament.add(jLTittleNewCompany);

        jPContent.setBackground(new java.awt.Color(236, 230, 240));
        jPContent.setForeground(new java.awt.Color(0, 0, 0));
        jPContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNameProyect.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLNameProyect.setForeground(new java.awt.Color(0, 0, 0));
        jLNameProyect.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLNameProyect.setText("Proyectos");
        jPContent.add(jLNameProyect, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLSectorStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLSectorStudent.setForeground(new java.awt.Color(0, 0, 0));
        jLSectorStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLSectorStudent.setText("Estudiantes");
        jPContent.add(jLSectorStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jCBProyects.setBackground(new java.awt.Color(255, 255, 255));
        jCBProyects.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCBProyects.setForeground(new java.awt.Color(0, 0, 0));
        jCBProyects.setMaximumSize(new java.awt.Dimension(300, 100));
        jCBProyects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProyectsActionPerformed(evt);
            }
        });
        jPContent.add(jCBProyects, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 140, -1));

        jBtnSaveProject.setBackground(new java.awt.Color(0, 0, 0));
        jBtnSaveProject.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jBtnSaveProject.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSaveProject.setText("ASIGNAR");
        jBtnSaveProject.setToolTipText("");
        jBtnSaveProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveProjectActionPerformed(evt);
            }
        });
        jPContent.add(jBtnSaveProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        jCBStudents.setBackground(new java.awt.Color(255, 255, 255));
        jCBStudents.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCBStudents.setForeground(new java.awt.Color(0, 0, 0));
        jCBStudents.setMaximumSize(new java.awt.Dimension(300, 100));
        jCBStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBStudentsActionPerformed(evt);
            }
        });
        jPContent.add(jCBStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 130, -1));

        jPButtom.setBackground(new java.awt.Color(236, 230, 240));
        jPButtom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPHead.setBackground(new java.awt.Color(236, 230, 240));
        jPHead.setForeground(new java.awt.Color(0, 0, 0));
        jPHead.setLayout(new javax.swing.BoxLayout(jPHead, javax.swing.BoxLayout.LINE_AXIS));

        lbTitleProyect.setAlignment(java.awt.Label.CENTER);
        lbTitleProyect.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbTitleProyect.setText("Sistema gestor de proyectos academicos");
        jPHead.add(lbTitleProyect);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTittleNewAssignament, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPHead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
            .addComponent(jPButtom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPTittleNewAssignament, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveProjectActionPerformed
        
        User estudiante = (User) jCBStudents.getSelectedItem();
        Project project = (Project) jCBProyects.getSelectedItem();
        
        try {
            project.assignStudent(estudiante);
            JOptionPane.showMessageDialog(null, "¡Proyecto Asignado!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jBtnSaveProjectActionPerformed

    private void jCBStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBStudentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBStudentsActionPerformed

    private void jCBProyectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProyectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBProyectsActionPerformed

    public void fillStudents() {
        jCBStudents.removeAllItems();
        for (User user : UsersStudents) {
            if (user.getRole().equals("ESTUDIANTE")) {
                jCBStudents.addItem(user);
            }
        }
    }
    
    public void fillProyects() {
        jCBProyects.removeAllItems();
            for (Project project : NameProyects){
            jCBProyects.addItem(project);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSaveProject;
    private javax.swing.JComboBox<Project> jCBProyects;
    private javax.swing.JComboBox<User> jCBStudents;
    private javax.swing.JLabel jLNameProyect;
    private javax.swing.JLabel jLSectorStudent;
    private javax.swing.JLabel jLTittleNewCompany;
    private javax.swing.JPanel jPButtom;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPTittleNewAssignament;
    private java.awt.Label lbTitleProyect;
    // End of variables declaration//GEN-END:variables
}
