/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.microkernel.gestionproyectos.presentation;

import co.edu.unicauca.microkernel.entities.Project;
import co.edu.unicauca.microkernel.entities.User;
import co.edu.unicauca.microkernel.interfaces.IProjectRepositoryPlugin;
import co.edu.unicauca.microkernel.interfaces.observer;
import co.unicauca.microkernel.gestionproyectos.core.domain.services.ProjectService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author lopez
 */
public class newProject extends javax.swing.JFrame{

    private IProjectRepositoryPlugin repositorio;
    private List<User> Users = new ArrayList<>();
    ProjectService project = new ProjectService(repositorio);
    /**
     * Creates new form newProject
     */
    public newProject(List<User> empresas, IProjectRepositoryPlugin plugin) {
        initComponents();
        this.Users = empresas;
        this.repositorio = plugin;
        this.project = new ProjectService(plugin);
        fillCompanies();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPButtom = new javax.swing.JPanel();
        jPContent = new javax.swing.JPanel();
        jLNameCompany = new javax.swing.JLabel();
        jFieldNameProject = new javax.swing.JTextField();
        jLSectorCompany = new javax.swing.JLabel();
        jCBCompany = new javax.swing.JComboBox<>();
        jBtnSaveProject = new javax.swing.JButton();
        jLDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescriptionProject = new javax.swing.JTextArea();
        jPTittleNewUser = new javax.swing.JPanel();
        jLTittleNewCompany = new javax.swing.JLabel();
        jPHead = new javax.swing.JPanel();
        lbTitleProyect = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPButtom.setBackground(new java.awt.Color(236, 230, 240));
        jPButtom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPContent.setBackground(new java.awt.Color(236, 230, 240));
        jPContent.setForeground(new java.awt.Color(0, 0, 0));
        jPContent.setLayout(new java.awt.GridBagLayout());

        jLNameCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLNameCompany.setForeground(new java.awt.Color(0, 0, 0));
        jLNameCompany.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLNameCompany.setText("Titulo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPContent.add(jLNameCompany, gridBagConstraints);

        jFieldNameProject.setBackground(new java.awt.Color(255, 255, 255));
        jFieldNameProject.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldNameProject.setForeground(new java.awt.Color(0, 0, 0));
        jFieldNameProject.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldNameProject.setText("Mi Proyecto");
        jFieldNameProject.setMaximumSize(new java.awt.Dimension(500, 100));
        jFieldNameProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldNameProjectActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPContent.add(jFieldNameProject, gridBagConstraints);

        jLSectorCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLSectorCompany.setForeground(new java.awt.Color(0, 0, 0));
        jLSectorCompany.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLSectorCompany.setText("Empresa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPContent.add(jLSectorCompany, gridBagConstraints);

        jCBCompany.setBackground(new java.awt.Color(255, 255, 255));
        jCBCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCBCompany.setForeground(new java.awt.Color(0, 0, 0));
        jCBCompany.setMaximumSize(new java.awt.Dimension(300, 100));
        jCBCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCompanyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPContent.add(jCBCompany, gridBagConstraints);

        jBtnSaveProject.setBackground(new java.awt.Color(0, 0, 0));
        jBtnSaveProject.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jBtnSaveProject.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSaveProject.setText("GUARDAR");
        jBtnSaveProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveProjectActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPContent.add(jBtnSaveProject, gridBagConstraints);

        jLDescription.setForeground(new java.awt.Color(0, 0, 0));
        jLDescription.setText("Descripcion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPContent.add(jLDescription, gridBagConstraints);

        jTADescriptionProject.setBackground(new java.awt.Color(255, 255, 255));
        jTADescriptionProject.setColumns(20);
        jTADescriptionProject.setForeground(new java.awt.Color(0, 0, 0));
        jTADescriptionProject.setRows(5);
        jScrollPane1.setViewportView(jTADescriptionProject);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        jPContent.add(jScrollPane1, gridBagConstraints);

        jPTittleNewUser.setBackground(new java.awt.Color(255, 255, 255));

        jLTittleNewCompany.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLTittleNewCompany.setForeground(new java.awt.Color(0, 0, 0));
        jLTittleNewCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittleNewCompany.setText("Nuevo Proyecto");
        jLTittleNewCompany.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPTittleNewUser.add(jLTittleNewCompany);

        jPHead.setBackground(new java.awt.Color(236, 230, 240));
        jPHead.setForeground(new java.awt.Color(0, 0, 0));
        jPHead.setLayout(new javax.swing.BoxLayout(jPHead, javax.swing.BoxLayout.LINE_AXIS));

        lbTitleProyect.setAlignment(java.awt.Label.CENTER);
        lbTitleProyect.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbTitleProyect.setText("Sistema gestor de proyectos academicos");
        jPHead.add(lbTitleProyect);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTittleNewUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPHead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addComponent(jPButtom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPTittleNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFieldNameProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldNameProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldNameProjectActionPerformed

    private void jBtnSaveProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveProjectActionPerformed
        // TODO add your handling code here:
        String titulo = jFieldNameProject.getText();
        User empresa = (User) jCBCompany.getSelectedItem();
        String descripcion = jTADescriptionProject.getText();
        try {
            project.registerProject(titulo, descripcion, empresa);
            JOptionPane.showMessageDialog(null, "¡Creado satisfactoriamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jBtnSaveProjectActionPerformed

    private void jCBCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBCompanyActionPerformed

    public void fillCompanies() {
        jCBCompany.removeAllItems();
        for (User user : Users) {
            if (user.getRole().equals("EMPRESA")) {
                jCBCompany.addItem(user);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSaveProject;
    private javax.swing.JComboBox<User> jCBCompany;
    private javax.swing.JTextField jFieldNameProject;
    private javax.swing.JLabel jLDescription;
    private javax.swing.JLabel jLNameCompany;
    private javax.swing.JLabel jLSectorCompany;
    private javax.swing.JLabel jLTittleNewCompany;
    private javax.swing.JPanel jPButtom;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPTittleNewUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTADescriptionProject;
    private java.awt.Label lbTitleProyect;
    // End of variables declaration//GEN-END:variables

}
