/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.microkernel.gestionproyectos.presentation;

import co.edu.unicauca.microkernel.entities.User;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author lopez
 */
public class newUser extends javax.swing.JFrame {

     private List<User> users;

    /**
     * Creates new form newUser
     */
    public newUser(List<User> users) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPButtom = new javax.swing.JPanel();
        jPContent = new javax.swing.JPanel();
        jLNameUser = new javax.swing.JLabel();
        jFieldNameUser = new javax.swing.JTextField();
        jLSectorUser = new javax.swing.JLabel();
        jCBRolUser = new javax.swing.JComboBox<>();
        jBtnSaveUser = new javax.swing.JButton();
        jLEmailUser = new javax.swing.JLabel();
        jFieldEmailUser = new javax.swing.JTextField();
        jPTittleNewUser = new javax.swing.JPanel();
        jLTittleNewUser = new javax.swing.JLabel();
        jPHead = new javax.swing.JPanel();
        lbTitleProyect = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPButtom.setBackground(new java.awt.Color(236, 230, 240));
        jPButtom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPContent.setBackground(new java.awt.Color(236, 230, 240));
        jPContent.setForeground(new java.awt.Color(0, 0, 0));
        jPContent.setLayout(new java.awt.GridBagLayout());

        jLNameUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLNameUser.setForeground(new java.awt.Color(0, 0, 0));
        jLNameUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLNameUser.setText("Titulo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPContent.add(jLNameUser, gridBagConstraints);

        jFieldNameUser.setBackground(new java.awt.Color(255, 255, 255));
        jFieldNameUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldNameUser.setForeground(new java.awt.Color(0, 0, 0));
        jFieldNameUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldNameUser.setText("Julian");
        jFieldNameUser.setMaximumSize(new java.awt.Dimension(500, 100));
        jFieldNameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldNameUserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPContent.add(jFieldNameUser, gridBagConstraints);

        jLSectorUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLSectorUser.setForeground(new java.awt.Color(0, 0, 0));
        jLSectorUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLSectorUser.setText("Rol");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPContent.add(jLSectorUser, gridBagConstraints);

        jCBRolUser.setBackground(new java.awt.Color(255, 255, 255));
        jCBRolUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCBRolUser.setForeground(new java.awt.Color(0, 0, 0));
        jCBRolUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COORDINADOR", "EMPRESA", "ESTUDIANTE" }));
        jCBRolUser.setMaximumSize(new java.awt.Dimension(300, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPContent.add(jCBRolUser, gridBagConstraints);

        jBtnSaveUser.setBackground(new java.awt.Color(0, 0, 0));
        jBtnSaveUser.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jBtnSaveUser.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSaveUser.setText("GUARDAR");
        jBtnSaveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveUserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPContent.add(jBtnSaveUser, gridBagConstraints);

        jLEmailUser.setForeground(new java.awt.Color(0, 0, 0));
        jLEmailUser.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPContent.add(jLEmailUser, gridBagConstraints);

        jFieldEmailUser.setBackground(new java.awt.Color(255, 255, 255));
        jFieldEmailUser.setForeground(new java.awt.Color(0, 0, 0));
        jFieldEmailUser.setText("micorre@gmail.com");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPContent.add(jFieldEmailUser, gridBagConstraints);

        jPTittleNewUser.setBackground(new java.awt.Color(255, 255, 255));

        jLTittleNewUser.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLTittleNewUser.setForeground(new java.awt.Color(0, 0, 0));
        jLTittleNewUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittleNewUser.setText("Nuevo usuario");
        jLTittleNewUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPTittleNewUser.add(jLTittleNewUser);

        jPHead.setBackground(new java.awt.Color(236, 230, 240));
        jPHead.setForeground(new java.awt.Color(0, 0, 0));
        jPHead.setLayout(new javax.swing.BoxLayout(jPHead, javax.swing.BoxLayout.LINE_AXIS));

        lbTitleProyect.setAlignment(java.awt.Label.CENTER);
        lbTitleProyect.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbTitleProyect.setText("Sistema gestor de proyectos academicos");
        jPHead.add(lbTitleProyect);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTittleNewUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPHead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jPButtom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPTittleNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFieldNameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldNameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldNameUserActionPerformed

    private void jBtnSaveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveUserActionPerformed
        // TODO add your handling code here:
        String nombre = jFieldNameUser.getText();
        String email = jFieldEmailUser.getText();
        String rol = jCBRolUser.getSelectedItem().toString();
        try {
            User user = new User("", "", "");
            user.registerUser(nombre, email, rol);
            JOptionPane.showMessageDialog(null, "¡Creado satisfactoriamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBtnSaveUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSaveUser;
    private javax.swing.JComboBox<String> jCBRolUser;
    private javax.swing.JTextField jFieldEmailUser;
    private javax.swing.JTextField jFieldNameUser;
    private javax.swing.JLabel jLEmailUser;
    private javax.swing.JLabel jLNameUser;
    private javax.swing.JLabel jLSectorUser;
    private javax.swing.JLabel jLTittleNewUser;
    private javax.swing.JPanel jPButtom;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPTittleNewUser;
    private java.awt.Label lbTitleProyect;
    // End of variables declaration//GEN-END:variables

}
